### ISSUE TITLE
DOCUMENT THE STEPS FOR END-USERS AND ADMIN

### ISSUE THREAD

**Issue by alidavid0418** [alam200/Perfumes2GoWS#11]
> 5. DOCUMENT THE STEPS FOR END-USERS AND ADMIN. PROVIDE ALL SOURCE-CODE BACK TO SITE OWNER.
> 6. MODIFY THE DISPLAY PAGE AFTER AN EDIT IS PERFORMED ON THE BACKEND

**Comment by alam200** [comment]
5...  This will be the last item once all enhancements are complete.
        a)  Steps to save inventory ,  customers  , orders in excel format from mongoDB to local PC folder
        b) Steps to cleanup inventory  and orders
       c) Steps to load fresh data

**Comment by alidavid0418** [comment]
@alam200 thanks 4 ur comment!
it's very helpful & cooperative to team work.

and, i get them all.

**Comment by alidavid0418** [comment]
> The document needs to be divided into three parts... Local PC, GIT and Prod. Also I need steps with screenshots to stop / sart services. You can update it as part for next project.
